### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by Joe3Ray** [xuexb/key-cache#6]
执行npm install时报错，见图

![image](https://cloud.githubusercontent.com/assets/5020273/16354014/c5161174-3ab8-11e6-9447-d63366de8da4.png)

**Comment by xuexb** [comment]
额，图看不到额，我的`node v4.4.3`、`npm v2.15.1`安装没问题

**Comment by xuexb** [comment]
额，我本地安装也没问题，测试环境使用`node 0.12, 4, 5, 6`安装都没问题额，是不是你的`babel`安装出错了

**Comment by Joe3Ray** [comment]
貌似是提示`.babelrc`配置没有`runtime`，你的`.babelrc`配置是啥样的？

**Comment by xuexb** [comment]
``` json
{
    "presets": [
      "es2015",
      "stage-0",
      "stage-3"
    ],
    "plugins": [
      "transform-runtime",
      "add-module-exports"
    ]
}
```

同 [@xuexb/key-cache/.babelrc](https://github.com/xuexb/key-cache/blob/master/.babelrc) 一致啊

**Comment by Joe3Ray** [comment]
昨晚fork的仓库没有`.babelrc`文件。。。我删掉重新fork了

**Comment by Joe3Ray** [comment]
重新fork之后有`.babelrc`了，也不报原来的`babel`编译错误，但是在安装`jformatter@stable`的时候出错

错误信息是：

```
No compatible version found: jformatter@stable
```
